### PR TITLE
Adding German translations

### PR DESCRIPTION
**Pull request by Than-DE**
#11 Added the translations in a new .arb file but I couldn't continue with the testing. Unfortunately, the app doesn't run in debug in my environment.

### CODE REVIEW

**Comment by Than-DE** [comment]
I actually just managed to run the app on my device. If you need me to actually implement the translation, let me know (haven't done that before).

**Comment by manuelvargastapia** [comment]
The implementation is straightforward. You just need to add the new file. However, you need also to add a bunch of automatically generated files to work with translations in this particular case. I do that with [Flutter Intl plugin](https://plugins.jetbrains.com/plugin/13666-flutter-intl) for VSCode. But I can do the test. Don't worry :+1: 

What problems did you have running the project? Let me know if you need clearer instructions, so I can improve the README file.

I'll close this PR when I finish the tests. The updates in FDroid usually take some time, nevertheless

**Comment by Than-DE** [comment]
Yeah I am using Android Studio, so not sure exactly how to set up the file generation. If you could run that, that would be great.

I will explain my problem + solution in a README pull request 👍

**Comment by manuelvargastapia** [comment]
Ok, I'll do the setup, and thanks for your feedback.

The plugin I mentioned is also available on Android Studio, btw. In case you need it, [this](https://www.raywenderlich.com/10794904-internationalizing-and-localizing-your-flutter-app) is a nice overview and tutorial to implement internationalization/localization in Flutter

**Pull request merged**
